<?php

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(apply_filters('plugin/acf/group_page_home', array(
		'key' => 'group_page_home',
		'title' => 'Ustawienia',
		'fields' => array (

			array (
				'key' => 'cf_home_offer',
				'label' => 'Oferta',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'cf_home_offer_section',
				'label' => 'Czy sekcja Oferta ma być wyświetlona?',
				'name' => 'cf_home_offer_section',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => 'box-important',
					'id' => '',
				),
				'choices' => array (
					0 => 'Nie',
					1 => 'Tak',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Nie',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'cf_home_offer_title',
				'label' => 'Tytuł',
				'name' => 'cf_home_offer_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'cf_home_offer_subtitle',
				'label' => 'Podtytuł',
				'name' => 'cf_home_offer_subtitle',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => 'br',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'cf_home_offer_offers',
				'label' => 'Oferty',
				'name' => 'cf_home_offer_offers',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'max' => 6,
				'layout' => 'block',
				'button_label' => 'Dodaj ofertę',
				'collapsed' => '',
				'sub_fields' => array (
					array (
						'key' => 'cf_home_offer_offers_icon',
						'label' => 'Ikona',
						'name' => 'cf_home_offer_offers_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => 'col-1-2',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'cf_home_offer_offers_title',
						'label' => 'Tytuł',
						'name' => 'cf_home_offer_offers_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => 'col-1-2',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'cf_home_offer_offers_text',
						'label' => 'Treść',
						'name' => 'cf_home_offer_offers_text',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => 'br',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),


			array (
				'key' => 'cf_home_contact',
				'label' => 'Kontakt',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'cf_home_contact_section',
				'label' => 'Czy sekcja Kontakt ma być wyświetlona?',
				'name' => 'cf_home_contact_section',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => 'box-important',
					'id' => '',
				),
				'choices' => array (
					0 => 'Nie',
					1 => 'Tak',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Nie',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'cf_home_contact_title',
				'label' => 'Tytuł',
				'name' => 'cf_home_contact_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'cf_home_contact_subtitle',
				'label' => 'Podtytuł',
				'name' => 'cf_home_contact_subtitle',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => 'br',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'cf_home_contact_form',
				'label' => 'Formularz kontaktowy',
				'name' => 'cf_home_contact_form',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'wpcf7_contact_form',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-index.php',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'comments',
			4 => 'slug',
			5 => 'author',
			6 => 'featured_image',
			7 => 'tags',
		),
		'active' => 1,
		'description' => '',
	)));

endif;